# .gqlgen.yml example
#
# Refer to https://gqlgen.com/config/
# for detailed .gqlgen.yml documentation.

schema: schema.graphql

exec:
  filename: generated.go

model:
  filename: types_gen.go

resolver:
  filename: resolver.go
  type: Resolver

models:
  SiteConnection:
    model: myplay_ground/gqlgen.SiteConnection
