// This file was generated by github.com/vektah/gqlgen, DO NOT EDIT

package gqlgen

type NewTodo struct {
	Text   string
	UserId string
}
type Todo struct {
	ID     string
	Text   string
	Done   bool
	UserID string
}
type User struct {
	ID   string
	Name string
}
